language: generic

branches:
  only:
    - master

os:
  - osx

matrix:
  include:
    - env: BUILD_OPTIONS=""
    - env: BUILD_OPTIONS="--devel"
    - env: BUILD_OPTIONS="--HEAD"
  fast_finish: true

before_install:
  - brew update

script:
  - brew install Formula/emacs-plus.rb $BUILD_OPTIONS
  - brew test Formula/emacs-plus.rb