name: Emacs 26

on:
  push:
    branches:
      - master
    paths:
      - "Formula/emacs-plus@26.rb"
      - "patches/emacs-26/**"
      - "Library/**"
      - ".github/workflows/emacs-26.yml"
  pull_request:
    paths:
      - "Formula/emacs-plus@26.rb"
      - "patches/emacs-26/**"
      - "Library/**"
      - ".github/workflows/emacs-26.yml"
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        build_opts:
          - ""
          - "--build-from-source"

    env:
      HOMEBREW_GITHUB_REF: ${{ github.head_ref || github.ref }}
      HOMEBREW_GITHUB_REPOSITORY: ${{ github.repository }}
      HOMEBREW_GITHUB_ACTOR: ${{ github.actor }}

    steps:
      - uses: actions/checkout@v1

      - name: Build emacs-plus@26 ${{ matrix.build_opts }}
        run: brew install emacs-plus@26.rb ${{ matrix.build_opts }}
        working-directory: Formula

      - name: Test installation
        if: contains(matrix.build_opts, '--HEAD') == false
        run: brew test emacs-plus@26.rb
        working-directory: Formula

      - name: Test installation (--HEAD)
        if: contains(matrix.build_opts, '--HEAD')
        run: brew test emacs-plus@26.rb --HEAD
        working-directory: Formula
