name: Emacs 28

on:
  push:
    branches:
      - master
    paths:
      - 'Formula/emacs-plus@28.rb'
      - 'patches/emacs-28/**'
      - 'Library/**'
      - '.github/workflows/emacs-28.yml'
  pull_request:
    paths:
      - 'Formula/emacs-plus@28.rb'
      - 'patches/emacs-28/**'
      - 'Library/**'
      - '.github/workflows/emacs-28.yml'
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build:

    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_opts:
          - ''
          - '--with-xwidgets'
          - '--with-no-titlebar'

    env:
      HOMEBREW_GITHUB_REF: ${{ github.head_ref || github.ref }}
      HOMEBREW_GITHUB_REPOSITORY: ${{ github.repository }}
      HOMEBREW_GITHUB_ACTOR: ${{ github.actor }}

    steps:
    - uses: actions/checkout@v1

    - name: Build emacs-plus@28 ${{ matrix.build_opts }}
      uses: nick-invision/retry@v1
      with:
        timeout_minutes: 300
        max_attempts: 2
        command: brew install Formula/emacs-plus@28.rb ${{ matrix.build_opts }}

    - name: Test installation
      if: contains(matrix.build_opts, '--HEAD') == false
      run: brew test Formula/emacs-plus@28.rb

    - name: Test installation (--HEAD)
      if: contains(matrix.build_opts, '--HEAD')
      run: brew test Formula/emacs-plus@28.rb --HEAD
