name: CI

on:
  push:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        build_opts: ['', '--build-from-source', '--with-no-titlebar', '--without-cocoa', '--without-cocoa --with-x11', '--HEAD']

    steps:
    - uses: actions/checkout@v1

    - name: Build emacs-plus ${{ matrix.build_opts }}
      run: brew install Formula/emacs-plus.rb ${{ matrix.build_opts }}

    - name: Test installation
      run: brew test Formula/emacs-plus.rb
